
export const commonStyles = {
    textMode: "dark:text-white text-text_light",
    bgMode: "bg-white dark:bg-el_dark",
    darkHoverBg: "dark:hover:bg-bg_dark",
    flexCenter: "flex justify-center items-center",
    flexCenterItems: "flex items-center",
    flexBetween: "flex items-center justify-between",
    flexJCenter: "flex justify-center",
    flexCol: "flex flex-col",
    flexCenterCol: "flex justify-center items-center flex-col",
    flexCenterStartCol: "flex justify-center items-start flex-col",
    flexItemsCenterCol: "flex items-center flex-col",
    flexCenterBetweenCol: "flex items-center justify-between flex-col",
    fontExtralight: "font-extralight opacity-80",
    styledDot: "after:rounded-[50%] dark:after:bg-white after:bg-text_light",
    smallDot: "after:w-2 after:h-2",
    bigDot: "after:w-4 after:h-4",
    transOpacity: "transition-opacity transform delay-200 duration-300 ease-in-out",
    transAll: "transition-all transform duration-300 ease-in-out",
    boldPb: "font-bold pb-3",
    fullWH: "w-full h-full",
    spaceX: "space-x-2",
    underlinePy: "py-1 underline",
    blockBoldMb: "block mb-2 font-bold",
    maxWidth1300: "max-w-[1300px] w-full flex-wrap",
    boldTextLG: "font-bold text-lg",
    h12p2wFullRound: "h-12 p-2 w-full rounded-md",
    gridCols: "grid grid-cols-1 min-[520px]:grid-cols-2 md:grid-cols-3 gap-1",
    borderRounded: "border border-bg_dark dark:border-bg_light rounded-md",
    absP2RoundShadow: "absolute px-2 rounded-md shadow-md"
}